[database]
    name     = "vulcanize_testing"
    hostname = "localhost"
    port     = 8077
    user     = "vdbm"
    password = "password"

[leveldb]
    path = "/Users/arijitdas/Library/Ethereum/rinkeby/geth/chaindata"
    ancient = "/Users/arijitdas/Library/Ethereum/rinkeby/geth/chaindata/ancient"

[snapshot]
    blockHeight = 58176