[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    user     = "postgres"

[leveldb]
    path = "/Users/user/Library/Ethereum/geth/chaindata"
    ancient = "/Users/user/Library/Ethereum/geth/chaindata/ancient"

[snapshot]
    mode = "file"
    workers = 4
    blockHeight = -1
    recoveryFile = "recovery_file"

[file]
    outputDir = "output_dir/"
