[database]
    name     = "vulcanize_testing"
    hostname = "localhost"
    port     = 8077
    user     = "vdbm"
    password = "password"

[leveldb]
    path = "/Users/iannorden/Library/Ethereum/geth/chaindata"
    ancient = "/Users/iannorden/Library/Ethereum/geth/chaindata/ancient"

[log]
    level = "info"
    file = "log_file"

[prom]
    metrics = true
    http = true
    httpAddr = "0.0.0.0"
    httpPort = 9101
    dbStats = true

[snapshot]
    mode = "file"
    workers = 4
    blockHeight = -1
    recoveryFile = "recovery_file"

[file]
    outputDir = "output_dir/"
