[database]
  name     = "vulcanize_public"
  hostname = "localhost"
  port     = 5432
  user     = "postgres"

[leveldb]
    path = "/Users/user/Library/Ethereum/geth/chaindata"

[snapshot]
    blockHeight = 0