[database]
    name     = "cerc_testing"
    hostname = "localhost"
    port     = 8077
    user     = "vdbm"
    password = "password"

[leveldb]
    path = "/Users/user/go/src/github.com/cerc-io/ipld-eth-state-snapshot/fixture/chain2data"
    ancient = "/Users/user/go/src/github.com/cerc-io/ipld-eth-state-snapshot/fixture/chain2data/ancient"

[log]
    level = "info"
    file = "log_file"

[prom]
    metrics = true
    http = true
    httpAddr = "0.0.0.0"
    httpPort = 9101
    dbStats = true

[snapshot]
    mode = "file"
    workers = 4
    blockHeight = 32
    recoveryFile = "recovery_file"

    startHeight = 1
    endHeight = 12

[file]
    outputDir = "output_dir/"

[ethereum]
    clientName = "Geth" # $ETH_CLIENT_NAME
    nodeID = "arch1" # $ETH_NODE_ID
    networkID = "1" # $ETH_NETWORK_ID
    chainID = "1" # $ETH_CHAIN_ID
    genesisBlock = "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3" # $ETH_GENESIS_BLOCK
